name: Copy env example
description: Copy env.example to .env

runs:
  using: composite

  steps:
    - name: Copy env example
      shell: bash
      run: find . -path './node_modules' -prune -o -type f -name ".env.example" -exec sh -c 'target="${1%.*}"; [ -e "$target" ] || cp "$1" "$target"' _ {} \;
