name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}-ci"
  cancel-in-progress: true

jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.14.2
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Copy env example
        uses: ./.github/actions/copy-env-example
      - name: Build
        run: pnpm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            .next/
            node_modules/
            tsconfig.tsbuildinfo
            .env
          retention-days: 1
      

  typecheck:
    name: Type Checking
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.14.2
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: 'pnpm'
      - name: Type check
        run: pnpm run typecheck

  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.14.2
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: 'pnpm'
      - name: Lint
        run: pnpm run lint
