name: Tweet PR Updates

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tweet-pr-update:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-artifacts
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.14.2
          run_install: false
      - uses: actions/setup-node@v5
        with:
          node-version: 22.18.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Run PR tweet automation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
          IFTTT_PR_TWEET_URL: ${{ secrets.IFTTT_PR_TWEET_URL }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          REPO_NAME: ${{ github.repository }}
        run: pnpm run pr-tweet
